baseURL: 
languageCode: en-us
title: Made With Laziness
theme: theme

params:
  author: Meetlink
  description: naja
  favicon: /favicon.ico
  
  nav:
    - name: source
      icon: fab fa-github
      url: https://github.com/rich25487/Teleporter

  bookmarks:
    - group: Monday
      items:
        - name: ประวัติศาสตร์
          url: https://meet.google.com/uyc-zosb-xrj
        - name: MoMo
          url: https://meet.google.com/lookup/a2p737w626
        - name: เคมี
          url: https://meet.google.com/zbf-ixqk-yoj
        - name: อังกฤษพื้น
          url: https://meet.google.com/lookup/bp2etabm7e
        - name: คณิตเพิ่ม
          url: https://meet.google.com/lookup/gvuikwcovx
       

        
    - group: Tuesday
      items:
        - name: คณิตพื้น
          url: https://meet.google.com/igu-csoi-avx
        - name: Amy's theater
          url: https://meet.google.com/ypv-mqhv-rjr
        - name: สังคม
          url: https://meet.google.com/vpg-zewa-acw
        - name: การเขียน
          url: https://meet.google.com/edr-oyvd-cqy
        - name: คณิตเพิ่ม
          url: https://meet.google.com/lookup/gvuikwcovx
        - name: ภาษาไทย
          url: https://meet.google.com/nwo-zpeo-qok
       

    - group: Wednesday
      items:
        - name: Amy's theater
          url: https://meet.google.com/ypv-mqhv-rjr
        - name: อังกฤษพื้น
          url: https://meet.google.com/lookup/bp2etabm7e
        - name: คณิตเพิ่ม
          url: https://meet.google.com/lookup/gvuikwcovx
        - name: ศิลปะ
          url: https://meet.google.com/lookup/ccuyi3lifg
       

    - group: Thursday
      items:
        - name: อังกฤษพื้น
          url: https://meet.google.com/lookup/bp2etabm7e
        - name: การเขียน
          url: https://meet.google.com/edr-oyvd-cqy
        - name: คณิตเพิ่ม
          url: https://meet.google.com/lookup/gvuikwcovx
        - name: สมศักดิ์
          url: https://meet.google.com/zbf-ixqk-yoj
        - name: COM
          url: https://meet.google.com/qyr-ssqr-vvp
        - name: วิทยาศาสตร์
          url: https://meet.google.com/zbf-ixqk-yoj
        

    - group: Friday
      items:
        - name: ภาษาไทย
          url: https://meet.google.com/nwo-zpeo-qok
        - name: สังคม
          url: https://meet.google.com/vpg-zewa-acw
        - name: การงาน
          url: https://meet.google.com/xdx-yntc-pos
        - name: คณิตพื้น
          url: https://meet.google.com/igu-csoi-avx 
      
    - group: 特別
      items: 
        - name: เช็คชื่อ
          url: https://meet.google.com/lookup/h6eugwqpqt
        - name: ภาษาไทย
          url: https://sites.google.com/obec.moe.go.th/benjamas6431102/home
       


    

    