baseURL: 
languageCode: en-us
title: Made With Laziness
theme: theme

params:
  author: Meetlink
  description: naja
  favicon: /favicon.ico
  
  nav:
    - name: source
      icon: fab fa-github
      url: https://github.com/rich25487/Teleporter

  bookmarks:
    - group: Monday
      items:
        
    - group: Tuesday
      items:
       

    - group: Wednesday
      items:
        - name: Amy's theater
          url: https://meet.google.com/ypv-mqhv-rjr
        - name: อังกฤษพื้น
          url: https://meet.google.com/lookup/bp2etabm7e
        - name: คณิตเพิ่ม
          url: https://meet.google.com/lookup/gvuikwcovx
        - name: ศิลปะ
          url: https://meet.google.com/lookup/ccuyi3lifg
       

    - group: Thursday
      items:
        

    - group: Friday
      items:   
        
    - group: 特別
      items: 
       


    

    