baseURL: 
languageCode: en-us
title: Made With Laziness
theme: theme

params:
  author: Meetlink
  description: naja
  favicon: /favicon.ico
  
  nav:
    - name: source
      icon: fab fa-github
      url: https://github.com/rich25487/Teleporter

  bookmarks:
    - group: Monday
      items:
        - name: อังกฤษพื้น
          url: https://meet.google.com/lookup/bp2etabm7e
        - name: คณิตเพิ่ม
          url: https://meet.google.com/lookup/gvuikwcovx

        
    - group: Tuesday
      items:
        - name: อังกฤษพื้น
          url: https://meet.google.com/lookup/bp2etabm7e
        - name: การเขียน
          url: https://meet.google.com/lookup/h2zlbqull
        - name: คณิตเพิ่ม
          url: https://meet.google.com/lookup/gvuikwcovx
       

    - group: Wednesday
      items:
        - name: Amy's theater
          url: https://meet.google.com/ypv-mqhv-rjr
        - name: อังกฤษพื้น
          url: https://meet.google.com/lookup/bp2etabm7e
        - name: คณิตเพิ่ม
          url: https://meet.google.com/lookup/gvuikwcovx
        - name: ศิลปะ
          url: https://meet.google.com/lookup/ccuyi3lifg
       

    - group: Thursday
      items:
        - name: อังกฤษพื้น
          url: https://meet.google.com/lookup/bp2etabm7e
        - name: การเขียน
          url: https://meet.google.com/lookup/h2zlbqull6
        - name: COM(No link)
          url: 
        - name: วิทยาศาสตร์(No link)
          url: 
        

    - group: Friday
      items: 
        - name: การงาน
          url: https://meet.google.com/lookup/crx4jm6wn6
        - name: คณิตพื้น
          url: https://meet.google.com/lookup/ahftnt5sze
        - name: Eng?(No link)
          url: 
      
    - group: 特別
      items: 
       


    

    